FROM ubuntu:26.04 AS common

WORKDIR /opt
SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PLENV_ROOT=/opt/.plenv
ENV PATH=$PLENV_ROOT/bin:$PLENV_ROOT/shims:$PATH

# The base image ships an 'ubuntu' user (UID 1000); recreate it with UID 55555
RUN userdel -r ubuntu 2>/dev/null || true \
  && useradd ubuntu -m -u 55555 \
  && echo "ubuntu:ubuntu" | chpasswd

RUN apt-get update && apt-get install -y --no-install-recommends \
        apt-file \
        apt-utils \
        build-essential \
        cmake \
        curl \
        fd-find \
        fish \
        git \
        htop \
        language-pack-ja-base \
        language-pack-ja \
        less \
        libbz2-dev \
        libcurl4-openssl-dev \
        libdeflate-dev \
        libgd-dev \
        libncurses-dev \
        libssl-dev \
        locales \
        make \
        nkf \
        openjdk-21-jdk-headless \
        openjdk-21-jre \
        patch \
        pkg-config \
        software-properties-common \
        sudo \
        tree \
        vim \
        wget \
    && echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections \
    && apt-get install -y --no-install-recommends ttf-mscorefonts-installer \
    && fc-cache -f \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists

# SAMtools
ENV version=1.24
COPY samtools-$version.tar.bz2 samtools-$version.tar.bz2
RUN tar xvfj samtools-$version.tar.bz2 \
    && cd samtools-$version \
    && ./configure \
    && make && make install \
    && rm /opt/samtools-$version.tar.bz2

# SRAtoolkit
ENV version=3.4.1
COPY sratoolkit.$version-ubuntu64.tar.gz sratoolkit.$version-ubuntu64.tar.gz
RUN tar zxvf sratoolkit.$version-ubuntu64.tar.gz \
    && mv sratoolkit.$version-ubuntu64/ /opt/sratoolkit.$version \
    && rm sratoolkit.$version-ubuntu64.tar.gz

# plenv
RUN git clone https://github.com/tokuhirom/plenv.git /opt/.plenv \
    && git clone https://github.com/tokuhirom/Perl-Build.git /opt/.plenv/plugins/perl-build/ \
    && echo 'eval "$(plenv init -)"' >> ~/.bashrc \
    && . ~/.bashrc \
    && plenv install 5.42.3 \
    && plenv global 5.42.3 \
    && plenv list-modules \
    && plenv install-cpanm \
    && cpanm -f Getopt::Long Math::CDF Excel::Writer::XLSX XML::Simple XSLoader \
        HTML::TreeBuilder LWP::Protocol::https Config::Std \
        Statistics::Distributions Path::Class Array::Utils Pod::Usage List::Util \
        Statistics::Swoop Spreadsheet::ParseExcel App::St CGI Statistics::Lite JSON File::Which \
        HTML::Template XML::Compile XML::Compile::SOAP11 XML::Compile::WSDL11 \
        XML::Compile::Transport::SOAPHTTP Log::Log4perl Font::TTF::Font Statistics::Basic \
        Config::General GD Clone Math::Round Params::Validate Math::Bezier List::MoreUtils IO::Socket::SSL \
        Math::VecStat Regexp::Common Set::IntSpan Readonly Text::Format SVG List::Util GD::Graph::lines \
        XML::LibXML XML::Compile XML::Compile::Cache XML::Compile::SOAP11 Test::LeakTrace \
    && rm -rf /root/.cpanm/work
#RUN cpanm Bio::ToolBox

RUN gpasswd -a ubuntu sudo

FROM ubuntu:26.04 AS normal
LABEL maintainer="Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>"
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PLENV_ROOT=/opt/.plenv
ENV PATH=$PLENV_ROOT/bin:$PLENV_ROOT/shims:$PATH:/opt/bin:/opt/sratoolkit.3.4.1/bin/:
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64/

COPY isnumber.sh /opt/bin/isnumber.sh

COPY --from=common / /
COPY ./.alias /root
RUN cat /root/.alias >> /root/.bashrc
USER ubuntu
WORKDIR /home/ubuntu
CMD ["/bin/bash"]

FROM nvidia/cuda:13.3.1-cudnn-runtime-ubuntu26.04 AS gpu
LABEL maintainer="Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>"
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PLENV_ROOT=/opt/.plenv
ENV PATH=$PLENV_ROOT/bin:$PLENV_ROOT/shims:$PATH:/opt/bin:/opt/sratoolkit.3.4.1/bin/:
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64/

COPY isnumber.sh /opt/bin/isnumber.sh

COPY --from=common / /
COPY ./.alias /root
RUN cat /root/.alias >> /root/.bashrc

USER ubuntu
WORKDIR /home/ubuntu
CMD ["/bin/bash"]
